# class Constant(object):
OPC_ITERATION_THRESHOLD = 20    # ILT迭代次数
OPC_TILE_SIZE = 2048 * 2048     # MASK大小
LITHOSIM_OFFSET = 512           # glp文件中坐标的原点
OPC_TILE_X = 2048   # MASK行数
OPC_TILE_Y = 2048   # MASK列数

MASK_TILE_END_X = LITHOSIM_OFFSET + 1280    # ?
MASK_TILE_END_Y = LITHOSIM_OFFSET + 1280    # ?
MASK_PRINTABLE_THRESHOLD = 0.5

OPC_LENGTH_CORNER_RESHAPE = 10