// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cuilt.proto

#ifndef PROTOBUF_INCLUDED_cuilt_2eproto
#define PROTOBUF_INCLUDED_cuilt_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_cuilt_2eproto 

namespace protobuf_cuilt_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_cuilt_2eproto
namespace cuilt {
class MosaicParameters;
class MosaicParametersDefaultTypeInternal;
extern MosaicParametersDefaultTypeInternal _MosaicParameters_default_instance_;
}  // namespace cuilt
namespace google {
namespace protobuf {
template<> ::cuilt::MosaicParameters* Arena::CreateMaybeMessage<::cuilt::MosaicParameters>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace cuilt {

// ===================================================================

class MosaicParameters : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:cuilt.MosaicParameters) */ {
 public:
  MosaicParameters();
  virtual ~MosaicParameters();

  MosaicParameters(const MosaicParameters& from);

  inline MosaicParameters& operator=(const MosaicParameters& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  MosaicParameters(MosaicParameters&& from) noexcept
    : MosaicParameters() {
    *this = ::std::move(from);
  }

  inline MosaicParameters& operator=(MosaicParameters&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const MosaicParameters& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const MosaicParameters* internal_default_instance() {
    return reinterpret_cast<const MosaicParameters*>(
               &_MosaicParameters_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(MosaicParameters* other);
  friend void swap(MosaicParameters& a, MosaicParameters& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline MosaicParameters* New() const final {
    return CreateMaybeMessage<MosaicParameters>(NULL);
  }

  MosaicParameters* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<MosaicParameters>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const MosaicParameters& from);
  void MergeFrom(const MosaicParameters& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MosaicParameters* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 OPC_ITERATION_THRESHOLD = 1;
  void clear_opc_iteration_threshold();
  static const int kOPCITERATIONTHRESHOLDFieldNumber = 1;
  ::google::protobuf::int32 opc_iteration_threshold() const;
  void set_opc_iteration_threshold(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:cuilt.MosaicParameters)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 opc_iteration_threshold_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_cuilt_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// MosaicParameters

// int32 OPC_ITERATION_THRESHOLD = 1;
inline void MosaicParameters::clear_opc_iteration_threshold() {
  opc_iteration_threshold_ = 0;
}
inline ::google::protobuf::int32 MosaicParameters::opc_iteration_threshold() const {
  // @@protoc_insertion_point(field_get:cuilt.MosaicParameters.OPC_ITERATION_THRESHOLD)
  return opc_iteration_threshold_;
}
inline void MosaicParameters::set_opc_iteration_threshold(::google::protobuf::int32 value) {
  
  opc_iteration_threshold_ = value;
  // @@protoc_insertion_point(field_set:cuilt.MosaicParameters.OPC_ITERATION_THRESHOLD)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace cuilt

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_cuilt_2eproto
