// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cuilt.proto

#include "cuilt.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace cuilt {
class MosaicParametersDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<MosaicParameters>
      _instance;
} _MosaicParameters_default_instance_;
}  // namespace cuilt
namespace protobuf_cuilt_2eproto {
static void InitDefaultsMosaicParameters() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::cuilt::_MosaicParameters_default_instance_;
    new (ptr) ::cuilt::MosaicParameters();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::cuilt::MosaicParameters::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_MosaicParameters =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsMosaicParameters}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_MosaicParameters.base);
}

::google::protobuf::Metadata file_level_metadata[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::cuilt::MosaicParameters, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::cuilt::MosaicParameters, opc_iteration_threshold_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::cuilt::MosaicParameters)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::cuilt::_MosaicParameters_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "cuilt.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\013cuilt.proto\022\005cuilt\"3\n\020MosaicParameters"
      "\022\037\n\027OPC_ITERATION_THRESHOLD\030\001 \001(\005b\006proto"
      "3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 81);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "cuilt.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_cuilt_2eproto
namespace cuilt {

// ===================================================================

void MosaicParameters::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int MosaicParameters::kOPCITERATIONTHRESHOLDFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

MosaicParameters::MosaicParameters()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_cuilt_2eproto::scc_info_MosaicParameters.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:cuilt.MosaicParameters)
}
MosaicParameters::MosaicParameters(const MosaicParameters& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  opc_iteration_threshold_ = from.opc_iteration_threshold_;
  // @@protoc_insertion_point(copy_constructor:cuilt.MosaicParameters)
}

void MosaicParameters::SharedCtor() {
  opc_iteration_threshold_ = 0;
}

MosaicParameters::~MosaicParameters() {
  // @@protoc_insertion_point(destructor:cuilt.MosaicParameters)
  SharedDtor();
}

void MosaicParameters::SharedDtor() {
}

void MosaicParameters::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* MosaicParameters::descriptor() {
  ::protobuf_cuilt_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_cuilt_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const MosaicParameters& MosaicParameters::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_cuilt_2eproto::scc_info_MosaicParameters.base);
  return *internal_default_instance();
}


void MosaicParameters::Clear() {
// @@protoc_insertion_point(message_clear_start:cuilt.MosaicParameters)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  opc_iteration_threshold_ = 0;
  _internal_metadata_.Clear();
}

bool MosaicParameters::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:cuilt.MosaicParameters)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 OPC_ITERATION_THRESHOLD = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &opc_iteration_threshold_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:cuilt.MosaicParameters)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:cuilt.MosaicParameters)
  return false;
#undef DO_
}

void MosaicParameters::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:cuilt.MosaicParameters)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 OPC_ITERATION_THRESHOLD = 1;
  if (this->opc_iteration_threshold() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->opc_iteration_threshold(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:cuilt.MosaicParameters)
}

::google::protobuf::uint8* MosaicParameters::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:cuilt.MosaicParameters)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 OPC_ITERATION_THRESHOLD = 1;
  if (this->opc_iteration_threshold() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->opc_iteration_threshold(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:cuilt.MosaicParameters)
  return target;
}

size_t MosaicParameters::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:cuilt.MosaicParameters)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // int32 OPC_ITERATION_THRESHOLD = 1;
  if (this->opc_iteration_threshold() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->opc_iteration_threshold());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void MosaicParameters::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:cuilt.MosaicParameters)
  GOOGLE_DCHECK_NE(&from, this);
  const MosaicParameters* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const MosaicParameters>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:cuilt.MosaicParameters)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:cuilt.MosaicParameters)
    MergeFrom(*source);
  }
}

void MosaicParameters::MergeFrom(const MosaicParameters& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:cuilt.MosaicParameters)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.opc_iteration_threshold() != 0) {
    set_opc_iteration_threshold(from.opc_iteration_threshold());
  }
}

void MosaicParameters::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:cuilt.MosaicParameters)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MosaicParameters::CopyFrom(const MosaicParameters& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:cuilt.MosaicParameters)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MosaicParameters::IsInitialized() const {
  return true;
}

void MosaicParameters::Swap(MosaicParameters* other) {
  if (other == this) return;
  InternalSwap(other);
}
void MosaicParameters::InternalSwap(MosaicParameters* other) {
  using std::swap;
  swap(opc_iteration_threshold_, other->opc_iteration_threshold_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata MosaicParameters::GetMetadata() const {
  protobuf_cuilt_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_cuilt_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace cuilt
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::cuilt::MosaicParameters* Arena::CreateMaybeMessage< ::cuilt::MosaicParameters >(Arena* arena) {
  return Arena::CreateInternal< ::cuilt::MosaicParameters >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
